# Generated by Django 4.0.1 on 2022-01-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0006_product_advanced_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='comment_pl',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pl',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='full_text_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='title_pl',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contentcategory',
            name='comment_pl',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contentcategory',
            name='name_pl',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='comment_pl',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='name_pl',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='advanced_description_pl',
            field=models.TextField(blank=True, null=True, verbose_name='Advanced description'),
        ),
        migrations.AddField(
            model_name='product',
            name='comment_pl',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_pl',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
