# Generated by Django 4.0.1 on 2022-01-31 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0007_category_comment_pl_category_name_pl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source_category',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='source_commercial',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='filter',
            field=models.ManyToManyField(blank=True, related_name='product_filter', to='navis.Filter'),
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('url', models.SlugField(max_length=300, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='commercial_image/')),
                ('source_commercial', models.CharField(blank=True, max_length=300, null=True)),
                ('source_category', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_category', to='navis.category')),
            ],
            options={
                'verbose_name': 'Commercial',
                'verbose_name_plural': 'Commercials',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_commercial', to='navis.commercial'),
        ),
    ]
