# Generated by Django 4.0.1 on 2022-02-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0008_product_source_category_product_source_commercial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_pl',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_uk',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
