# Generated by Django 4.0.1 on 2022-02-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navis', '0009_alter_category_name_alter_category_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog_image/'),
        ),
        migrations.AddField(
            model_name='category',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Info'),
        ),
        migrations.AddField(
            model_name='category',
            name='source_category',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_pl',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_uk',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
